.TH GIT-PROMOTE 1
.SH NAME
git promote \- Merges one base branch into another
.SH SYNOPSIS
.B git promote
.IR [--remote|--push]
.SH DESCRIPTION
.B
Merges one base branch into another.
.SH OPTIONS
.TP
.BR \-p ", " \-\-push
Pushes to the remote when complete. Can be configured to always push in `.gbrc` config file
.TP
.BR \-R ", " \-\-remote
Specifies the remote to pull from and push to.
