.TH GIT-UPDATE 1
.SH NAME
git update \- Update a branch from its base branch
.SH SYNOPSIS
.B git update
.IR  [--remote|--push]
.SH DESCRIPTION
.B
Update the current branch from its base branch
.SH OPTIONS
.TP
.BR \-p ", " \-\-push
Pushes to the remote when complete. Can be configured to always push in `.gbrc` config file
.TP
.BR \-R ", " \-\-remote
Specifies the remote to push to.  Only valid when pushing.
