.TH GIT-BETTER-INIT 1
.SH NAME
git better-init \- Creates a config file based off of an example config
.SH SYNOPSIS
.B git better-init
.IR [--global]\ [exampleName]
.SH DESCRIPTION
.B
Creates a config file based off of an example config within the current repo.  If no example is provided a blank config file is created.  When passing the `--global` flag, it will create a config file in the user's home directory for use in all projects.
.SH OPTIONS
.TP
.BR \-g ", " \-\-global
Makes a `.gbrc` config file in the user's home directory for use in all projects
