.TH GIT-START 1
.SH NAME
git start \- Create a new branch based off of a specific base branch
.SH SYNOPSIS
.B git start
.IR [workflow]\ branchName
.SH DESCRIPTION
.B
Create a new branch based off of a specific base branch based on workflows.
.SH OPTIONS
.TP
.BR \-R ", " \-\-remote
Specifies the remote to update from before creating a new branch.
