.TH GIT-FINISH 1
.SH NAME
git finish \- Finishes a branch by merging it into its base(es) and deleting it
.SH SYNOPSIS
.B git finish
.IR [--remote|--push]
.SH DESCRIPTION
.B
Finishes a branch by merging it into its base(es) and deleting it
.SH OPTIONS
.TP
.BR \-p ", " \-\-push
Pushes to the remote when complete. Can be configured to always push in `.gbrc` config file
.TP
.BR \-R ", " \-\-remote
Specifies the remote to push to.  Only valid when pushing.
